/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current PM5 connection status. */
        get: operations["getConnection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full current live state, for the initial dashboard render. */
        get: operations["getLiveSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multiplexed live event stream (Server-Sent Events).
         * @description A text/event-stream carrying named events. Each SSE `event:` field is one of connection | workout | metrics | stroke | forceCurve | heartbeat, and its `data:` is the JSON of the correspondingly-named schema (enumerated by LiveEvent). Clients connect with EventSource and dispatch on the event name; on reconnect, re-fetch /live/snapshot to resync.
         */
        get: operations["streamLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stored sessions. */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The active source feeding the live pipeline. */
        get: operations["getSource"];
        put?: never;
        /** Select and start the source (live PM5 or replay a stored session). */
        post: operations["startSource"];
        /** Stop the active source. */
        delete: operations["stopSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan for nearby PM5s (for the connect picker). */
        get: operations["scanDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ConnectionState: "DISCONNECTED" | "SEARCHING" | "CONNECTING" | "CONNECTED" | "RECONNECTING";
        DeviceInfo: {
            /** @description Advertised name, e.g. "PM5 432234859 Row". */
            name: string;
            serial?: string | null;
            /** @description CoreBluetooth peripheral UUID (per host). */
            address: string;
        };
        ConnectionStatus: {
            state: components["schemas"]["ConnectionState"];
            device?: components["schemas"]["DeviceInfo"] | null;
            /** @description PM5 firmware revision string. */
            firmware?: string | null;
            /** @description Firmware decode profile in use. */
            profileId?: string | null;
            /**
             * Format: date-time
             * @description When this state was entered.
             */
            since?: string;
        };
        /** @enum {string} */
        WorkoutDurationType: "TIME" | "DISTANCE" | "OTHER";
        /** @enum {string} */
        WorkoutPhase: "WAITING" | "ROWING" | "RESTING" | "ENDED";
        WorkoutState: {
            /** @description Raw PM5 workout-type enum. */
            type?: number;
            durationType: components["schemas"]["WorkoutDurationType"];
            /** @description Fixed-time target (s). */
            targetTimeS?: number | null;
            /** @description Fixed-distance target (m). */
            targetDistanceM?: number | null;
            phase: components["schemas"]["WorkoutPhase"];
            intervalCount?: number;
        };
        /** @description Coherent snapshot of the latest values merged across PM5 characteristics. */
        LiveMetrics: {
            elapsedTimeS: number;
            distanceM: number;
            powerW: number;
            /** @description Current pace, seconds per 500 m. */
            paceSecondsPer500?: number;
            avgPaceSecondsPer500?: number;
            /** @description Strokes per minute. */
            strokeRate: number;
            /** @description null = no HR belt. */
            heartRateBpm?: number | null;
            dragFactor?: number;
            /** @description Fixed-time pieces. */
            timeLeftS?: number | null;
            /** @description Fixed-distance pieces. */
            distanceLeftM?: number | null;
            projectedTimeS?: number | null;
            projectedDistanceM?: number | null;
            totalCalories?: number;
            splitAvgPowerW?: number | null;
            splitAvgPaceSecondsPer500?: number | null;
        };
        StrokeSummary: {
            /** @description Monotonic stroke index. */
            index: number;
            pmTime: number;
            drivePeakForceN?: number;
            avgDriveForceN?: number;
            driveTimeS?: number;
            powerW?: number;
            strokeDistanceM?: number;
        };
        ForceCurve: {
            strokeIndex: number;
            pmTime?: number;
            /** @description Ordered drive-force samples, in Newtons. */
            forcesN: number[];
            peakN?: number;
        };
        LiveSnapshot: {
            connection: components["schemas"]["ConnectionStatus"];
            workout?: components["schemas"]["WorkoutState"] | null;
            metrics?: components["schemas"]["LiveMetrics"] | null;
            lastStroke?: components["schemas"]["StrokeSummary"] | null;
            lastForceCurve?: components["schemas"]["ForceCurve"] | null;
        };
        Heartbeat: {
            /** Format: date-time */
            t: string;
        };
        /** @description Documents the possible SSE payloads. On the wire these are separate named SSE events (see the /live/stream description), not a wrapper object; this oneOf enumerates the `data:` payloads. */
        LiveEvent: components["schemas"]["ConnectionStatus"] | components["schemas"]["WorkoutState"] | components["schemas"]["LiveMetrics"] | components["schemas"]["StrokeSummary"] | components["schemas"]["ForceCurve"] | components["schemas"]["Heartbeat"];
        SessionSummary: {
            /** @description Session folder name. */
            id: string;
            startedAt?: string | null;
            device?: string | null;
            firmware?: string | null;
            distanceM?: number | null;
            strokes?: number | null;
            durationS?: number | null;
            avgPowerW?: number | null;
            peakPowerW?: number | null;
            /** @description Has raw frames, so it can be replayed. */
            replayable: boolean;
        };
        /** @enum {string} */
        SourceType: "NONE" | "BLE" | "REPLAY";
        /** @description Select a source. type=ble connects to a PM5 (optional device name); type=replay plays a stored session (sessionId, optional speed multiplier, default 1.0 = real time). */
        SourceRequest: {
            /** @enum {string} */
            type: "ble" | "replay";
            device?: string | null;
            sessionId?: string | null;
            speed?: number | null;
        };
        SourceStatus: {
            sourceType: components["schemas"]["SourceType"];
            connection: components["schemas"]["ConnectionStatus"];
            /** @description The session being replayed, if any. */
            sessionId?: string | null;
        };
        DiscoveredDevice: {
            name: string;
            address: string;
            rssi?: number | null;
        };
        /** @description RFC 7807 problem details. */
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current connection status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
        };
    };
    getLiveSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current live snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveSnapshot"];
                };
            };
        };
    };
    streamLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open SSE stream (does not terminate until the client disconnects). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LiveEvent"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current source status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
        };
    };
    startSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            /** @description The source that was started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
            /** @description Invalid request (e.g. unknown or non-replayable session). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stopSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source stopped; current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
        };
    };
    scanDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nearby PM5s. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveredDevice"][];
                };
            };
        };
    };
}
