/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current PM5 connection status. */
        get: operations["getConnection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full current live state, for the initial dashboard render. */
        get: operations["getLiveSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multiplexed live event stream (Server-Sent Events).
         * @description A text/event-stream carrying named events. Each SSE `event:` field is one of connection | workout | metrics | stroke | forceCurve | heartbeat, and its `data:` is the JSON of the correspondingly-named schema (enumerated by LiveEvent). Clients connect with EventSource and dispatch on the event name; on reconnect, re-fetch /live/snapshot to resync.
         */
        get: operations["streamLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stored sessions. */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-session index — stored sessions with their technique scores, filterable. */
        get: operations["getSessionIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A metric over time across sessions.
         * @description Technique-shape metrics (catchGradient, peakPosition, finishPlateau, meanMaxRatio) are comparable across any pieces and may span the whole log. Performance metrics (avgPowerW, peakPowerW, distanceM, durationS) are only comparable within a workout type — scope them with the filters (e.g. targetType + a distance band) so incomparable pieces are not mixed.
         */
        get: operations["getTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The active source feeding the live pipeline. */
        get: operations["getSource"];
        put?: never;
        /** Select and start the source (live PM5 or replay a stored session). */
        post: operations["startSource"];
        /** Stop the active source. */
        delete: operations["stopSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan for nearby PM5s (for the connect picker). */
        get: operations["scanDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/export.fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a stored session as a Garmin .FIT rowing activity.
         * @description Returns the session as a FIT activity file (records, per-split laps, and a rowing session summary) for upload to Strava / Garmin Connect / Concept2 Logbook. The controller is hand-written (binary streaming), like /live/stream.
         */
        get: operations["exportSessionFit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deterministic technique analysis of a stored session's force curves.
         * @description Per-stroke shape features (peak, peak position, catch gradient, finish plateau, hump index…), a Kleshnev-grounded scorecard, a mean±band average curve, per-feature drift trends, the resampled per-stroke curves (for a heatmap/overlay), and deterministic fault flags. Computed locally, no model. `hasCurves=false` when the session has no force-curve data.
         */
        get: operations["getSessionAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether an LLM coach provider is configured (so the UI can show the panel). */
        get: operations["getLlmStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LLM coaching for a stored session (only when a provider is configured).
         * @description Grounded natural-language technique coaching built from the session's deterministic analysis (features + scorecard + flags) and a Kleshnev rubric. Optional — 409 when no provider is configured. The model never sees raw curves.
         */
        get: operations["getSessionCoach"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved dashboard profiles. */
        get: operations["listDashboards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboards/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile name (must be a safe filename — no path separators or ".."). */
                name: string;
            };
            cookie?: never;
        };
        /** Fetch one dashboard profile. */
        get: operations["getDashboard"];
        /** Create or replace a dashboard profile. */
        put: operations["putDashboard"];
        post?: never;
        /** Delete a dashboard profile. */
        delete: operations["deleteDashboard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ConnectionState: "DISCONNECTED" | "SEARCHING" | "CONNECTING" | "CONNECTED" | "RECONNECTING";
        DeviceInfo: {
            /** @description Advertised name, e.g. "PM5 432234859 Row". */
            name: string;
            serial?: string | null;
            /** @description CoreBluetooth peripheral UUID (per host). */
            address: string;
        };
        ConnectionStatus: {
            state: components["schemas"]["ConnectionState"];
            device?: components["schemas"]["DeviceInfo"] | null;
            /** @description PM5 firmware revision string. */
            firmware?: string | null;
            /** @description Firmware decode profile in use. */
            profileId?: string | null;
            /**
             * Format: date-time
             * @description When this state was entered.
             */
            since?: string;
        };
        /** @enum {string} */
        WorkoutDurationType: "TIME" | "DISTANCE" | "OTHER";
        /** @enum {string} */
        WorkoutPhase: "WAITING" | "ROWING" | "RESTING" | "ENDED";
        WorkoutState: {
            /** @description Raw PM5 workout-type enum. */
            type?: number;
            durationType: components["schemas"]["WorkoutDurationType"];
            /** @description Fixed-time target (s). */
            targetTimeS?: number | null;
            /** @description Fixed-distance target (m). */
            targetDistanceM?: number | null;
            phase: components["schemas"]["WorkoutPhase"];
            intervalCount?: number;
        };
        /** @description Coherent snapshot of the latest values merged across PM5 characteristics. */
        LiveMetrics: {
            elapsedTimeS: number;
            distanceM: number;
            powerW: number;
            /** @description Current pace, seconds per 500 m. */
            paceSecondsPer500?: number;
            avgPaceSecondsPer500?: number;
            /** @description Strokes per minute. */
            strokeRate: number;
            /** @description null = no HR belt. */
            heartRateBpm?: number | null;
            dragFactor?: number;
            /** @description Fixed-time pieces. */
            timeLeftS?: number | null;
            /** @description Fixed-distance pieces. */
            distanceLeftM?: number | null;
            projectedTimeS?: number | null;
            projectedDistanceM?: number | null;
            totalCalories?: number;
            splitAvgPowerW?: number | null;
            splitAvgPaceSecondsPer500?: number | null;
        };
        StrokeSummary: {
            /** @description Monotonic stroke index. */
            index: number;
            pmTime: number;
            drivePeakForceN?: number;
            avgDriveForceN?: number;
            driveTimeS?: number;
            powerW?: number;
            strokeDistanceM?: number;
        };
        ForceCurve: {
            strokeIndex: number;
            pmTime?: number;
            /** @description Ordered drive-force samples, in Newtons. */
            forcesN: number[];
            peakN?: number;
        };
        LiveSnapshot: {
            connection: components["schemas"]["ConnectionStatus"];
            workout?: components["schemas"]["WorkoutState"] | null;
            metrics?: components["schemas"]["LiveMetrics"] | null;
            lastStroke?: components["schemas"]["StrokeSummary"] | null;
            lastForceCurve?: components["schemas"]["ForceCurve"] | null;
        };
        Heartbeat: {
            /** Format: date-time */
            t: string;
        };
        /** @description Documents the possible SSE payloads. On the wire these are separate named SSE events (see the /live/stream description), not a wrapper object; this oneOf enumerates the `data:` payloads. */
        LiveEvent: components["schemas"]["ConnectionStatus"] | components["schemas"]["WorkoutState"] | components["schemas"]["LiveMetrics"] | components["schemas"]["StrokeSummary"] | components["schemas"]["ForceCurve"] | components["schemas"]["Heartbeat"];
        SessionSummary: {
            /** @description Session folder name. */
            id: string;
            startedAt?: string | null;
            device?: string | null;
            firmware?: string | null;
            distanceM?: number | null;
            strokes?: number | null;
            durationS?: number | null;
            avgPowerW?: number | null;
            peakPowerW?: number | null;
            /** @description Has raw frames, so it can be replayed. */
            replayable: boolean;
        };
        /** @description One session's summary plus its cached technique scores, for cross-session comparison. */
        SessionIndexEntry: {
            id: string;
            startedAt?: string | null;
            /**
             * @description Workout duration type.
             * @enum {string}
             */
            targetType: "time" | "distance" | "none";
            /** @description Target seconds (time) or metres (distance). */
            targetValue?: number | null;
            distanceM?: number | null;
            durationS?: number | null;
            avgPowerW?: number | null;
            peakPowerW?: number | null;
            /** @description Whether force curves were recorded (so scores exist). */
            hasCurves: boolean;
            /** @description Technique score key → value (catchGradient, peakPosition, finishPlateau, meanMaxRatio). */
            scores?: {
                [key: string]: number;
            };
            replayable: boolean;
        };
        SessionTrendPoint: {
            sessionId: string;
            startedAt?: string | null;
            value: number;
        };
        /** @enum {string} */
        SourceType: "NONE" | "BLE" | "REPLAY";
        /** @description Select a source. type=ble connects to a PM5 (optional device name); type=replay plays a stored session (sessionId, optional speed multiplier, default 1.0 = real time). */
        SourceRequest: {
            /** @enum {string} */
            type: "ble" | "replay";
            device?: string | null;
            sessionId?: string | null;
            speed?: number | null;
        };
        SourceStatus: {
            sourceType: components["schemas"]["SourceType"];
            connection: components["schemas"]["ConnectionStatus"];
            /** @description The session being replayed, if any. */
            sessionId?: string | null;
        };
        DiscoveredDevice: {
            name: string;
            address: string;
            rssi?: number | null;
        };
        /** @description Opaque dashboard configuration (widgets + grid layout + per-widget config). The server stores and returns it verbatim and does NOT interpret its internals, so the browser's widget model can evolve without a contract change. */
        DashboardConfig: {
            [key: string]: unknown;
        };
        DashboardSummary: {
            name: string;
        };
        Dashboard: {
            name: string;
            config: components["schemas"]["DashboardConfig"];
        };
        /** @description Deterministic technique analysis of a session's force curves. */
        SessionAnalysis: {
            id: string;
            /** @description Strokes analysed (with a force curve). */
            strokes: number;
            /** @description False if the session stored no force curves. */
            hasCurves: boolean;
            /** @description Resample resolution: points per normalized drive. */
            bins?: number;
            scorecard?: components["schemas"]["ScoreMetric"][];
            /** @description Average drive-force curve with a ±1σ band, over normalized drive position. */
            meanCurve?: components["schemas"]["CurveBand"][];
            /** @description Each stroke resampled to `bins` force values (N) — for the heatmap / overlay. */
            curves?: number[][];
            features?: components["schemas"]["FeatureStat"][];
            trends?: components["schemas"]["FeatureTrend"][];
            flags?: components["schemas"]["TechniqueFlag"][];
        };
        /** @description One shape metric scored against a Kleshnev target window. */
        ScoreMetric: {
            key: string;
            label: string;
            value?: number | null;
            unit?: string;
            targetMin?: number | null;
            targetMax?: number | null;
            pass?: boolean | null;
            note?: string | null;
        };
        CurveBand: {
            /** @description Normalized drive position 0..1. */
            x: number;
            mean: number;
            lower: number;
            upper: number;
        };
        FeatureStat: {
            key: string;
            label: string;
            unit?: string;
            avg?: number | null;
            /** @description Coefficient of variation (consistency). */
            cv?: number | null;
            min?: number | null;
            max?: number | null;
        };
        FeatureTrend: {
            key: string;
            label: string;
            unit?: string;
            points: components["schemas"]["TrendPoint"][];
        };
        TrendPoint: {
            stroke: number;
            value: number;
        };
        TechniqueFlag: {
            code: string;
            /** @enum {string} */
            severity: "info" | "warn";
            message: string;
            /** @description Strokes affected, where applicable. */
            count?: number | null;
        };
        LlmStatus: {
            /** @description True if an LLM coach provider is set up. */
            configured: boolean;
            /** @description e.g. ollama | openai | anthropic. */
            provider?: string | null;
            model?: string | null;
        };
        CoachResult: {
            /** @description The model that produced the coaching. */
            model: string;
            /** @description Natural-language technique coaching. */
            text: string;
        };
        /** @description One turn in the agent conversation (the transcript is held client-side). */
        ChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        /** @description The client-held transcript; the last message is the new user question. */
        ChatRequest: {
            messages: components["schemas"]["ChatMessage"][];
        };
        /** @description RFC 7807 problem details. */
        Problem: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current connection status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionStatus"];
                };
            };
        };
    };
    getLiveSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current live snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveSnapshot"];
                };
            };
        };
    };
    streamLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open SSE stream (does not terminate until the client disconnects). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LiveEvent"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    getSessionIndex: {
        parameters: {
            query?: {
                /** @description Only workouts with this target type. */
                targetType?: "time" | "distance";
                /** @description Minimum distance (m). */
                distanceMin?: number;
                /** @description Maximum distance (m). */
                distanceMax?: number;
                /** @description Inclusive lower bound on startedAt (ISO-8601). */
                from?: string;
                /** @description Inclusive upper bound on startedAt (ISO-8601). */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching sessions (newest first) with technique scores. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionIndexEntry"][];
                };
            };
        };
    };
    getTrend: {
        parameters: {
            query: {
                /** @description catchGradient | peakPosition | finishPlateau | meanMaxRatio | avgPowerW | peakPowerW | distanceM | durationS */
                metric: string;
                targetType?: "time" | "distance";
                distanceMin?: number;
                distanceMax?: number;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trend points, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionTrendPoint"][];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current source status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
        };
    };
    startSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRequest"];
            };
        };
        responses: {
            /** @description The source that was started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
            /** @description Invalid request (e.g. unknown or non-replayable session). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    stopSource: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source stopped; current status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
        };
    };
    scanDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nearby PM5s. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveredDevice"][];
                };
            };
        };
    };
    exportSessionFit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session as a FIT activity file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.ant.fit": string;
                };
            };
            /** @description No such session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSessionAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session's technique analysis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionAnalysis"];
                };
            };
            /** @description No such session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getLlmStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LLM coach status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatus"];
                };
            };
        };
    };
    getSessionCoach: {
        parameters: {
            query?: {
                /** @description single (default) coaches this session alone; progress also grounds the athlete's recent same-type history from the cross-session index and narrates improvement over time (falling back to single when there is no comparable history). */
                mode?: "single" | "progress";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coaching text and the model that produced it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachResult"];
                };
            };
            /** @description No such session. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No LLM provider configured. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDashboards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved dashboard profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"][];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile name (must be a safe filename — no path separators or ".."). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dashboard profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description No such profile. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    putDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile name (must be a safe filename — no path separators or ".."). */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DashboardConfig"];
            };
        };
        responses: {
            /** @description The stored profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Invalid profile name. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Profile name (must be a safe filename — no path separators or ".."). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such profile. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
